# The URL the site will be built for
base_url = "https://b.tinyops.ru"

title = "Блог Уильяма Оккама"
# a description; you can use markdown here if you like
description="\"*Не следует привлекать новые сущности без крайней на то необходимости*\""
default_language = "ru"

highlight_theme = "base16-ocean-dark"
generate_feed = true
feed_limit = 100

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Gutenberg
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

taxonomies = [
 {name = "tags", paginate_by = 30},
 {name = "categories", paginate_by = 30}
]

[markdown]
highlight_code = true

[extra]
keywords = "блог"

# FAVICON
favicon_type = "image/x-icon"

# ABOUT PAGE
enable_about_blog_page = true

# BUTTONS
website = "tinyops.ru"
website_button_title = "TinyOps"
website_button_hint = "Перейти на сайт"

github = "tinyops-ru"
github_button_title = "GitHub"
github_button_hint = "Перейти на мою страницу в Github"

twitter = "mental_foreplay"
twitter_button_title = "Twitter"
twitter_button_hint = "Перейти в мой Twitter"

email = "your@email.com"
email_button_title = "Написать"
email_button_hint = "Написать мне на почту"

instagram = "soel79"
instagram_button_title = "Instagram"
instagram_button_hint = "Перейти на мою страницу в Instagram"

# youtube = ""
youtube_button_title = "YouTube"
youtube_button_hint = "Перейти на мой канал в YouTube"

# OPEN GRAPH
open_graph_url = "https://b.tinyops.ru"
open_graph_type = "blog"
open_graph_title = "William of Ockham Blog"
open_graph_image = ""

#------------------------------------------
# YANDEX
#------------------------------------------

# Yandex.WebMaster
yandex_webmaster_verification_code = ""

# Yandex Metrika
yandex_metrika_counter = ""

# Yandex Turbo Pages
# https://yandex.ru/dev/turbo/
yandex_turbo_pages = false
